version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: olx
    binary: olx
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
      - >-
        {{- if eq .Os "darwin" }}
          {{- if eq .Arch "amd64"}}CC=o64-clang{{- end }}
          {{- if eq .Arch "arm64"}}CC=aarch64-apple-darwin20.2-clang{{- end }}
        {{- end }}
        {{- if eq .Os "windows" }}
          {{- if eq .Arch "amd64" }}CC=x86_64-w64-mingw32-gcc{{- end }}
        {{- end }}
      - >-
        {{- if eq .Os "darwin" }}
          {{- if eq .Arch "amd64"}}CXX=o64-clang+{{- end }}
          {{- if eq .Arch "arm64"}}CXX=aarch64-apple-darwin20.2-clang++{{- end }}
        {{- end }}
        {{- if eq .Os "windows" }}
          {{- if eq .Arch "amd64" }}CXX=x86_64-w64-mingw32-g++{{- end }}
        {{- end }}

archives:
  - formats: [ 'tar.gz' ]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

brews:
  - name: "olx"
    ids:
      - olx
    commit_author:
      name: goreleaserbot
      email: goreleaser@gha.com
    description: "A CLI tool for OLX"
    homepage: "https://github.com/andresgarcia29/olx-cli"
    install: |
      bin.install "olx"
    test: |
      system "#{bin}/olx", "--version"
    repository:
      owner: andresgarcia29
      name: homebrew-agm
      branch: main

    dependencies:
      - name: git
        os: mac
      - name: zsh
        type: optional
      - name: fish
        version: v1.2.3
      - name: elvish
        type: optional
        version: v1.2.3
