name: Build & Push service
on:
  push:
    branches:
      - main

jobs:
  # service-tests:
  #   name: Test service
  #   runs-on: ubuntu-latest

  #   permissions:
  #     contents: "read"

  #   steps:
  #     - id: checkout
  #       name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup NodeJS
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: "20.x"

  #     - name: Install dependencies
  #       run: |
  #         npm install

  #     - name: Check Linter
  #       run: |
  #         npm run lint

  get-version:
    name: Get Next Version
    runs-on: ubuntu-latest

    permissions:
      contents: "write"
      id-token: "write"

    outputs:
      version: ${{ steps.get-version.outputs.version }}

    steps:
      - id: get-version
        name: Get Version From Semantic Release
        uses: andresgarcia29/gha-common-workflows/actions/get-version@main
        with:
          github-token: ${{ secrets.GH_TOKEN }}

  build-go-app-and-upload-binary:
    name: Build & Push Binary
    runs-on: ubuntu-latest
    needs: [get-version]

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - id: build-go-app-and-upload-binary
        name: Build And Push Docker Image
        uses: andresgarcia29/gha-common-workflows/actions/build-go-app-and-upload-binary@main
        with:
          aws_region: us-east-1
          aws_ecr_role_arn: arn:aws:iam::455222299354:role/github_oidc
          aws_bucket_name: agm-open-applications
          go_version: 1.23
          app_name: olx
          app_version: ${{ needs.get-version.outputs.version }}

  goreleaser:
    name: Run GoReleaser
    runs-on: ubuntu-latest
    needs: [get-version]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: ${{ needs.get-version.outputs.version }}
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build-go-app-and-upload-binary, goreleaser]

    permissions:
      contents: write
      id-token: write

    outputs:
      version: ${{ steps.get-version.outputs.version }}

    steps:
      - id: release
        name: Release With Semantic Release
        uses: andresgarcia29/gha-common-workflows/actions/release@main
        with:
          github-token: ${{ secrets.GH_TOKEN }}
